apiVersion: v1
kind: Namespace
metadata:
  name: cab-booking-production
  labels:
    environment: production
    app: cab-booking
---
apiVersion: v1
kind: Namespace
metadata:
  name: cab-booking-staging
  labels:
    environment: staging
    app: cab-booking
