name: vercel-deploy

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
    paths:
      - 'frontend/**'

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Vercel CLI
        run: npm i -g vercel@latest

      - name: Pull Vercel Env
        working-directory: frontend
        run: vercel pull --yes --environment=production --token=${{ env.VERCEL_TOKEN }}

      - name: Build
        working-directory: frontend
        run: vercel build --prod --token=${{ env.VERCEL_TOKEN }}

      - name: Deploy
        working-directory: frontend
        run: vercel deploy --prebuilt --prod --token=${{ env.VERCEL_TOKEN }}

